services:
  # server:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     PORT: 3000
#     PGUSER: postgres
  #     PGPASSWORD: postgres
  #     PGHOST: localhost
  #     PGPORT: 5432
  #     PGDATABASE: todo
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/postgres:/docker-entrypoint-initdb.d/
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@dev.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - ./data/pgadmin/servers.json:/pgadmin4/servers.json

volumes:
  postgres_data:
