services:
  server:
    build: .
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      # Configure `pg` client
      # See: https://node-postgres.com/features/connecting
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: todo
    develop:
      watch:
        - path: ./src
          action: rebuild
        - path: ./package.json
          action: rebuild
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/postgres:/docker-entrypoint-initdb.d/
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@dev.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - ./data/pgadmin/servers.json:/pgadmin4/servers.json

volumes:
  postgres_data:
